# import labiraries

In [10]:
import numpy as np 
import pandas as pd 

# # import Dataset

In [11]:
dataset = pd.read_csv("weatherAUS.csv")
X = dataset.iloc[:,[1,2,3,4,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21]].values
Y = dataset.iloc[:,-1].values
print(X)

[['Albury' 13.4 22.9 ... 16.9 21.8 'No']
 ['Albury' 7.4 25.1 ... 17.2 24.3 'No']
 ['Albury' 12.9 25.7 ... 21.0 23.2 'No']
 ...
 ['Uluru' 5.4 26.9 ... 12.5 26.1 'No']
 ['Uluru' 7.8 27.0 ... 15.1 26.0 'No']
 ['Uluru' 14.9 nan ... 15.0 20.9 'No']]


# Changing y into 2d array for input

In [12]:
Y = Y.reshape(-1,1) 

In [13]:
print(Y)

[['No']
 ['No']
 ['No']
 ...
 ['No']
 ['No']
 [nan]]


# data processing

In [14]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan,strategy='most_frequent')
X = imputer.fit_transform(X)
Y = imputer.fit_transform(Y)

In [15]:
 print(X)

[['Albury' 13.4 22.9 ... 16.9 21.8 'No']
 ['Albury' 7.4 25.1 ... 17.2 24.3 'No']
 ['Albury' 12.9 25.7 ... 21.0 23.2 'No']
 ...
 ['Uluru' 5.4 26.9 ... 12.5 26.1 'No']
 ['Uluru' 7.8 27.0 ... 15.1 26.0 'No']
 ['Uluru' 14.9 20.0 ... 15.0 20.9 'No']]


In [16]:
print(Y)

[['No']
 ['No']
 ['No']
 ...
 ['No']
 ['No']
 ['No']]


# encoding dataset

In [17]:
from sklearn.preprocessing import LabelEncoder
le1 = LabelEncoder()
X[:,0] = le1.fit_transform(X[:,0])
le2 = LabelEncoder()
X[:,4] = le2.fit_transform(X[:,4])
le3 = LabelEncoder()
X[:,6] = le3.fit_transform(X[:,6])
le4 = LabelEncoder()
X[:,7] = le4.fit_transform(X[:,7])
le5 = LabelEncoder()
X[:,-1] = le5.fit_transform(X[:,-1])
le6 = LabelEncoder()
Y[:,-1] = le6.fit_transform(Y[:,-1])


In [18]:
print(X)

[[2 13.4 22.9 ... 16.9 21.8 0]
 [2 7.4 25.1 ... 17.2 24.3 0]
 [2 12.9 25.7 ... 21.0 23.2 0]
 ...
 [41 5.4 26.9 ... 12.5 26.1 0]
 [41 7.8 27.0 ... 15.1 26.0 0]
 [41 14.9 20.0 ... 15.0 20.9 0]]


In [19]:
print(Y)

[[0]
 [0]
 [0]
 ...
 [0]
 [0]
 [0]]


# feature scaling

In [20]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

In [21]:
print(X)

[[-1.53166617  0.19132753 -0.04135977 ... -0.01407077  0.02310362
  -0.52979545]
 [-1.53166617 -0.75105231  0.26874452 ...  0.03244663  0.387799
  -0.52979545]
 [-1.53166617  0.11279588  0.35331842 ...  0.62166712  0.22733303
  -0.52979545]
 ...
 [ 1.20928479 -1.06517892  0.52246622 ... -0.69632607  0.65037966
  -0.52979545]
 [ 1.20928479 -0.68822699  0.53656187 ... -0.29317521  0.63579185
  -0.52979545]
 [ 1.20928479  0.42692249 -0.45013361 ... -0.30868102 -0.10818671
  -0.52979545]]


# train_test_split

In [22]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.3,random_state=0)

In [23]:
print(X_train)

[[-0.75857743  1.7619606   1.35410955 ...  1.86213129  1.42353385
  -0.52979545]
 [-1.46138537 -1.81908279 -0.28098582 ... -1.06846532 -0.22488923
  -0.52979545]
 [-1.39110458  0.96093773  0.24055322 ...  0.38908008  0.32944774
  -0.52979545]
 ...
 [ 1.0687232   0.75675544  0.93124006 ...  1.10234698  1.07342629
  -0.52979545]
 [ 0.57675765 -0.04426743 -0.16822062 ...  0.01694083 -0.28324049
   1.88752093]
 [ 1.63096955 -0.0285611  -0.91529006 ... -0.35519842 -0.76463838
  -0.52979545]]


In [24]:
print(Y_train)

[[0]
 [0]
 [0]
 ...
 [0]
 [0]
 [0]]


# Training Model

In [25]:
le_target = LabelEncoder()
Y_train = le_target.fit_transform(Y_train.ravel())  # Use ravel() to convert Y_train to a 1D array

le_target = LabelEncoder()
Y_test = le_target.fit_transform(Y_test.ravel())  # Use ravel() to convert Y_test to a 1D array

from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=100,random_state=0)
classifier.fit(X_train,Y_train)

classifier.score(X_train,Y_train)

0.9999312525780283

# Calculate and print the classifier's score on the training data

In [26]:
train_score = classifier.score(X_train, Y_train)
print(f'Training Accuracy: {train_score * 100:.2f}%')

Training Accuracy: 99.99%


# Calculate and print the classifier's score on the test data

In [27]:
test_score = classifier.score(X_test, Y_test)
print(f'Test Accuracy: {test_score * 100:.2f}%')

y_pred = le6.inverse_transform(np.array(classifier.predict(X_test),dtype=int))
Y_test = le6.inverse_transform(np.array(Y_test,dtype=int))

y_pred = y_pred.reshape(-1,1)
Y_test = Y_test.reshape(-1,1)


df = np.concatenate((Y_test,y_pred),axis=1)
dataframe = pd.DataFrame(df,columns=['Rain on Tommorrow','Predition of Rain'])

Test Accuracy: 85.36%


In [28]:
print(dataframe)

      Rain on Tommorrow Predition of Rain
0                   Yes                No
1                   Yes                No
2                    No                No
3                    No               Yes
4                    No                No
...                 ...               ...
43633                No                No
43634                No                No
43635                No                No
43636                No                No
43637                No               Yes

[43638 rows x 2 columns]


In [29]:
from sklearn.metrics import accuracy_score
accuracy=accuracy_score(Y_test,y_pred)

print(f'Accuracy: {accuracy * 100:.2f}%')

Accuracy: 85.36%


In [30]:
import pandas as pd

# Use a raw string for the file path
file_path = r"C:\Users\91987\Downloads\RAIN PREDICTION\weatherAUS.csv"

# Read the CSV file using pd.read_csv
dataset = pd.read_csv(file_path)

# Display basic information about the dataset
print("Dataset Overview:")
print(dataset.info())

# Display summary statistics
print("\nSummary Statistics:")
print(dataset.describe())

# Check for missing values
print("\nMissing Values:")
print(dataset.isnull().sum())

# Explore unique values in categorical columns
print("\nUnique Values in Categorical Columns:")
for column in dataset.select_dtypes(include=["object"]).columns:
    print(f"{column}: {dataset[column].unique()}")

# Visualize distributions and relationships using EDA plots (matplotlib, seaborn)

# Perform additional data preprocessing steps as needed

# Generate a report summarizing your observations and any preprocessing steps
# ...

# Save the preprocessed dataset if necessary
# dataset.to_csv(r"path\to\preprocessed_dataset.csv", index=False)


Dataset Overview:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145460 entries, 0 to 145459
Data columns (total 23 columns):
 #   Column         Non-Null Count   Dtype  
---  ------         --------------   -----  
 0   Date           145460 non-null  object 
 1   Location       145460 non-null  object 
 2   MinTemp        143975 non-null  float64
 3   MaxTemp        144199 non-null  float64
 4   Rainfall       142199 non-null  float64
 5   Evaporation    82670 non-null   float64
 6   Sunshine       75625 non-null   float64
 7   WindGustDir    135134 non-null  object 
 8   WindGustSpeed  135197 non-null  float64
 9   WindDir9am     134894 non-null  object 
 10  WindDir3pm     141232 non-null  object 
 11  WindSpeed9am   143693 non-null  float64
 12  WindSpeed3pm   142398 non-null  float64
 13  Humidity9am    142806 non-null  float64
 14  Humidity3pm    140953 non-null  float64
 15  Pressure9am    130395 non-null  float64
 16  Pressure3pm    130432 non-null  float64
 17  Cloud9am   